### ISSUE TITLE
Can't decode current authentication responses

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-ruby#1]
Affects forum https://github.com/blockstack/blockstack-browser/issues/561

```
(blockstack) Callback phase initiated.
(blockstack) Authentication failure! invalid_auth_response: Blockstack::InvalidAuthResponse, Unable to decode JWT

Blockstack::InvalidAuthResponse (Unable to decode JWT):
  blockstack (0.5.9) lib/blockstack.rb:79:in `rescue in verify_auth_response'
  blockstack (0.5.9) lib/blockstack.rb:44:in `verify_auth_response'
  /Users/larry/git/omniauth-blockstack/lib/omniauth/strategies/blockstack.rb:71:in `callback_phase'
  omniauth (1.4.2) lib/omniauth/strategy.rb:227:in `callback_call'
  omniauth (1.4.2) lib/omniauth/strategy.rb:184:in `call!'
  omniauth (1.4.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.4.2) lib/omniauth/builder.rb:63:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  activerecord (4.0.13) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.0.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  activerecord (4.0.13) lib/active_record/migration.rb:373:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.13) lib/active_support/callbacks.rb:373:in `_run__1766841012064838309__call__callbacks'
  activesupport (4.0.13) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/reloader.rb:64:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.13) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.13) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.13) lib/rails/engine.rb:511:in `call'
  railties (4.0.13) lib/rails/application.rb:97:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  rack (1.5.5) lib/rack/handler/webrick.rb:60:in `service'
  /Users/larry/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /Users/larry/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /Users/larry/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /Users/larry/.rvm/gems/ruby-2.3.3/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/_source.erb (0.5ms)
  Rendered /Users/larry/.rvm/gems/ruby-2.3.3/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/_trace.erb (0.9ms)
  Rendered /Users/larry/.rvm/gems/ruby-2.3.3/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (0.8ms)
  Rendered /Users/larry/.rvm/gems/ruby-2.3.3/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (33.7ms)
```

**Comment by larrysalibra** [comment]
This was already fixed.
